run:
  timeout: 5m

linters:
  enable:
    - govet
    - gosimple
    - ineffassign
    - gofmt
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
