version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    container_name: fortune-backend

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    depends_on:
      - backend
    container_name: fortune-frontend
