services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=redis
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    depends_on:
      - backend
