apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000