name: Lint (golangci)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: backend
          version: v1.60.3
      - uses: actions/setup-go@v5
        with:
          go-version-file: frontend/go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: frontend
          version: v1.60.3
