name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Files needing format
        run: |
          gofmt -s -l backend || true
          gofmt -s -l frontend || true
